server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user

        - id: dossier-service
          uri: lb://dossier-service
          predicates:
            - Path=/api/dossiers/**
          filters:
            - name: CircuitBreaker
              args:
                name: dossierService
                fallbackUri: forward:/fallback/dossier

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentService
                fallbackUri: forward:/fallback/payment

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG